# app/models/dimension_score.py

from uuid import UUID
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, model_validator
from app.models.enumerations import Dimension

# DEFAULT WEIGHTS PER DIMENSION
# Loaded from app.core.settings so they stay in sync with the canonical
# Pydantic Settings class and can be overridden via environment variables.
# Total weights must sum to 1.0 (enforced by the Settings model_validator).

from app.core.settings import get_settings as _get_settings


def _load_dimension_weights() -> dict:
    s = _get_settings()
    return {
        Dimension.DATA_INFRASTRUCTURE: s.W_DATA_INFRA,
        Dimension.AI_GOVERNANCE:       s.W_AI_GOVERNANCE,
        Dimension.TECHNOLOGY_STACK:    s.W_TECH_STACK,
        Dimension.TALENT_SKILLS:       s.W_TALENT,
        Dimension.LEADERSHIP_VISION:   s.W_LEADERSHIP,
        Dimension.USE_CASE_PORTFOLIO:  s.W_USE_CASES,
        Dimension.CULTURE_CHANGE:      s.W_CULTURE,
    }


DIMENSION_WEIGHTS = _load_dimension_weights()


# BASE SCHEMA
# Contains all common fields shared between Create and Response schemas
class DimensionScoreBase(BaseModel):
    """
    Base Pydantic model for DimensionScore.
    
    Requirements satisfied:
    - Assessment foreign key reference (assessment_id: UUID)
    - Dimension type enum (dimension: Dimension)
    - Score 0-100, required (score: float with ge=0, le=100)
    - Weight 0-1, dimension-specific default (weight: Optional[float])
    - Confidence level 0-1 (confidence: float with ge=0, le=1)
    - Evidence count (evidence_count: int with ge=0)
    """
    
    # Foreign key reference to the Assessment entity
    assessment_id: UUID = Field(
        ...,
        description="UUID of the associated assessment (foreign key)"
    )
    
    # Dimension type from the Dimension enum
    dimension: Dimension = Field(
        ...,
        description="Type of dimension being scored (from Dimension enum)"
    )
    
    # Score value between 0-100 (required field)
    score: float = Field(
        ...,  # Required field (no default)
        ge=0,  # Greater than or equal to 0
        le=100,  # Less than or equal to 100
        description="Score value between 0 and 100"
    )
    
    # Weight value between 0-1 (optional, will be auto-set based on dimension)
    weight: Optional[float] = Field(
        default=None,  # Will be set by validator if not provided
        ge=0,  # Greater than or equal to 0
        le=1,  # Less than or equal to 1
        description="Weight of this dimension (0-1), auto-assigned based on dimension type if not provided"
    )
    
    # Confidence level between 0-1 (defaults to 0.8)
    confidence: float = Field(
        default=0.8,  # Default confidence level
        ge=0,  # Greater than or equal to 0
        le=1,  # Less than or equal to 1
        description="Confidence level of the score (0-1)"
    )
    
    # Count of evidence pieces supporting this score
    evidence_count: int = Field(
        default=0,  # Default to 0 evidence pieces
        ge=0,  # Must be non-negative
        description="Number of evidence pieces supporting this score"
    )
    # MODEL VALIDATOR
    # Runs after all field validations to set default weight based on dimension

    
    @model_validator(mode='after')
    def set_default_weight(self) -> 'DimensionScoreBase':
        """
        Automatically assigns default weight based on dimension type.
        
        This validator runs after all field validations are complete.
        If weight is not provided (None), it looks up the default weight
        from DIMENSION_WEIGHTS dictionary based on the dimension type.
        Falls back to 0.1 if dimension is not found in the dictionary.
        
        Returns:
            self: The validated model instance with weight set
        """
        if self.weight is None:
            # Look up default weight for this dimension, fallback to 0.1
            self.weight = DIMENSION_WEIGHTS.get(self.dimension, 0.1)
        return self


# Used for creating new DimensionScore records via POST requests

class DimensionScoreCreate(DimensionScoreBase):
    """
    Schema for creating a new DimensionScore.
    
    Inherits all fields from DimensionScoreBase.
    Used in POST /api/v1/assessments/{id}/scores endpoint.
    
    Note: UUID primary key (id) is NOT included here as it will be
    auto-generated by the database upon creation.
    """
    pass


# UPDATE SCHEMA
# Used for updating existing DimensionScore records via PUT requests


class DimensionScoreUpdate(BaseModel):
    """
    Schema for updating an existing DimensionScore.
    
    All fields are optional to allow partial updates.
    Used in PUT /api/v1/scores/{id} endpoint.
    """
    
    dimension: Optional[Dimension] = Field(
        default=None,
        description="Type of dimension being scored"
    )
    
    score: Optional[float] = Field(
        default=None,
        ge=0,
        le=100,
        description="Score value between 0 and 100"
    )
    
    weight: Optional[float] = Field(
        default=None,
        ge=0,
        le=1,
        description="Weight of this dimension (0-1)"
    )
    
    confidence: Optional[float] = Field(
        default=None,
        ge=0,
        le=1,
        description="Confidence level of the score (0-1)"
    )
    
    evidence_count: Optional[int] = Field(
        default=None,
        ge=0,
        description="Number of evidence pieces supporting this score"
    )



# RESPONSE SCHEMA
# Used for returning DimensionScore data in API responses


class DimensionScoreResponse(DimensionScoreBase):
    """
    Schema for DimensionScore API responses.
    
    Inherits all fields from DimensionScoreBase and adds:
    - id: UUID primary key (auto-generated)
    - created_at: Timestamp of record creation
    
    Requirements satisfied:
    - UUID primary key (id: UUID)
    
    Used in responses for:
    - POST /api/v1/assessments/{id}/scores (201 Created)
    - GET /api/v1/assessments/{id}/scores (200 OK)
    - PUT /api/v1/scores/{id} (200 OK)
    """
    
    # UUID primary key - auto-generated by database
    id: UUID = Field(
        ...,
        description="Unique identifier for the dimension score (primary key)"
    )
    
    # Timestamp of when the record was created
    created_at: datetime = Field(
        ...,
        description="Timestamp when the dimension score was created"
    )

    class Config:
        """Pydantic configuration for ORM compatibility."""
        # Allows the model to read data from ORM objects (SQLAlchemy models)
        from_attributes = True